Added: carbon stats and coming soon card on the home page
pellartech/carbon-ios pull request #23
Opened 2023-03-17 08:12 UTC by iosdevashok

[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

### Description
TODO

### Pull requests checks where applicable
- [ ] Fill in the three TODOs above (tickets number and description of your work)
- [ ] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

2023-03-17 08:13 UTC, iosdevashok commented
@madtocc  Ive completed both tickets (#16 and #17 ) and pushed on the same branch. 
![Simulator Screen Shot - iPhone 14 - 2023-03-17 at 13 41 41](https://user-images.githubusercontent.com/102407838/225849439-8df55b1a-a98d-4bc3-9be8-3116e28318dd.png)

2023-03-19 19:44 UTC, madtocc requested changes

2023-03-19 19:44 UTC, madtocc commented on Client/Assets/Images.xcassets/ic_bridge.imageset/ic_bridge.png
add icon without background. pdf are preferred or a bit higher. quality of icon seems not ok on phone.

2023-03-19 19:44 UTC, madtocc commented on Client/Assets/Images.xcassets/ic_stacking.imageset/ic_stacking.png
add icon without background. pdf are preferred or a bit higher. quality of icon seems not ok on phone.

2023-03-19 19:44 UTC, madtocc commented on Client/Assets/Images.xcassets/ic_swap.imageset/ic_swap.png
add icon without background. pdf are preferred or a bit higher. quality of icon seems not ok on phone.

2023-03-19 19:44 UTC, madtocc commented on Client/Assets/Images.xcassets/ic_wallet.imageset/ic_wallet.png
add icon without background. pdf are preferred or a bit higher. quality of icon seems not ok on phone.

2023-03-19 19:44 UTC, madtocc commented on Client/Frontend/Home/LogoHeader/HomeLogoHeaderCell.swift
add a view with gradient background + cornerRadius instead of just the image

2023-03-22 04:06 UTC, iosdevashok commented
![Simulator Screen Shot - iPhone 14 - 2023-03-22 at 09 35 51](https://user-images.githubusercontent.com/102407838/226799574-2552ebac-88bd-40bd-8293-e1e740aa9a22.png)

2023-03-22 20:41 UTC, madtocc approved these changes

2023-03-22 20:41 UTC, merged