Completed: New onboarding screen
pellartech/carbon-ios pull request #27
Opened 2023-03-23 16:53 UTC by iosdevashok

[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

### Description
TODO

### Pull requests checks where applicable
- [ ] Fill in the three TODOs above (tickets number and description of your work)
- [ ] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

2023-03-23 16:59 UTC, iosdevashok commented
https://user-images.githubusercontent.com/102407838/227279053-91b3e554-b11e-4429-970b-cc62b3fbfdbc.mp4

2023-03-23 20:54 UTC, madtocc requested changes

2023-03-23 20:54 UTC, madtocc commented on Client/Frontend/Intro/IntroViewController.swift
Whenever you remove code, avoid commenting out the code. You can erase the code not used. If we want to throw back we can revert.

2023-03-23 20:54 UTC, madtocc commented on Client/Frontend/Intro/IntroViewController.swift
Can we still use the page control? Looks like we have lost the functionality to scroll and move to the other page.

2023-03-23 20:54 UTC, madtocc commented on Client/Frontend/Intro/OnboardingViewController.swift
the last page should have a "Done" or "Next" button at the bottom to be able to dismiss the on boarding modal.

2023-03-24 18:52 UTC, madtocc requested changes
All good now, however when scrolling manually instead of clicking next the page indicator does not change.
Scroll back and forward should update the current page index.
currently just hitting next updates the page indicator.

2023-03-28 21:30 UTC, madtocc commented
We should keep the manual scroll, the scroll should update the indicator...

2023-03-30 21:35 UTC, madtocc commented
@iosdevashok 
There are 2 page indicators. We don't need the one on the bottom (grey).

Expected:
When clicking "Next" it should move forward and change the orange indicator.
When you swipe left or right the orange indicator should change according to the page.

Current:
When you click on next it changes the orange indicator ✅
manually swiping it does not change the orange indicator ❌ 
Shows a grey indicator next to the bottom of the page  ❌

https://user-images.githubusercontent.com/12486417/228969210-20b0ab83-25a1-41dc-a4ea-e6f439c33635.mov

2023-03-31 16:37 UTC, merged